newhardhat function

diff --git a/shell/shellrc.d/function b/shell/shellrc.d/function
--- a/shell/shellrc.d/function
+++ b/shell/shellrc.d/function
@@ -71,6 +71,52 @@ function newbuild(){
     chmod +x "build.sh"
 }
 
+function newhardhat(){
+    local projName=${1:?'missing project name'}
+    (
+    mkdir ${projName} && cd ${projName}
+    echo "initialize project.."
+    npm init -y
+    npm install --save-dev hardhat || { echo "install hardhat failed"; return 1; }
+    npm install --save-dev @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers ethers || { echo "install related packages failed"; return 1; }
+    npm install --save-dev hardhat-deploy || { echo "install hardhat-deploy failed"; return 1; }
+    _sampleDeploy
+    npx hardhat
+    )
+}
+
+function _sampleDeploy(){
+    mkdir deploy && cd deploy
+    cat>00-sample.js<<-EOF
+const hre = require('hardhat')
+module.exports = async ({
+                            getNamedAccounts,
+                            deployments,
+                            getChainId,
+                            getUnnamedAccounts,
+                        }) => {
+    const {deploy} = deployments;
+
+    // const {deployer} = await getNamedAccounts();
+    // console.log("deployer: ",deployer)
+
+    const [owner, controller, user1, user2, user3] = await hre.ethers.getSigners();
+
+    console.log("wait for deploy..")
+    const tx = await deploy('ERC1155Music', {
+        from: owner.address,
+        proxy: true,
+        // args:['https://abc.com']
+    });
+    console.log("contract(proxy) address: ",tx.address)
+    console.log("tx hash: ",tx.transactionHash)
+    console.log("receipt: ",tx.receipt)
+    console.log("implementation: ",tx.implementation)
+};
+EOF
+    cd -
+}
+
 function append_path(){
     if [ -z "$1" ];then
         return
