newsh script

diff --git a/shell/shellrc.d/newsh b/shell/shellrc.d/newsh
--- a/shell/shellrc.d/newsh
+++ b/shell/shellrc.d/newsh
@@ -99,7 +99,7 @@ _runAsRoot(){
 			Error: this installer needs the ability to run commands as root.
 			We are unable to find either "sudo" or "su" available to make this happen.
 			EOF
-            exit 1
+            return 1
         fi
     fi
 
@@ -184,7 +184,11 @@ _run(){
         fi
     else
         if [ $trace -eq 1 ];then
-            set -x; ${bash_c} "${cmd}";set +x;
+            set -x
+            ${bash_c} "${cmd}"
+            local ret=$?
+            set +x;
+            return ${ret}
         else
             ${bash_c} "${cmd}"
         fi
@@ -194,14 +198,14 @@ _run(){
 function _root(){
     if [ ${EUID} -ne ${rootID} ];then
         echo "Requires root privilege." 1>&2
-        exit 1
+        return 1
     fi
 }
 
 function _linux(){
     if [ "$(uname)" != "Linux" ];then
         echo "Requires Linux" 1>&2
-        exit 1
+        return 1
     fi
 }
 
@@ -215,6 +219,39 @@ function _wait(){
        : $((secs--))
     done
     echo -ne "\033[0K\r"
+}
+
+_must_ok(){
+    if [ $? != 0 ];then
+        echo "failed,exit.."
+        exit $?
+    fi
+}
+
+_info(){
+    echo -n "$(date +%FT%T) ${1}"
+}
+
+_infoln(){
+    echo "$(date +%FT%T) ${1}"
+}
+
+_error(){
+    echo -n "$(date +%FT%T) ${RED}${1}${NORMAL}"
+}
+
+_errorln(){
+    echo "$(date +%FT%T) ${RED}${1}${NORMAL}"
+}
+
+_checkService(){
+    _info "find service ${1}.."
+    if systemctl --all --no-pager | grep -q "${1}";then
+        echo "OK"
+    else
+        echo "Not found"
+        return 1
+    fi
 }
 
 ed=vi
